# Generated by Django 3.2 on 2021-04-22 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_isbn_isbn_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isbn',
            old_name='id',
            new_name='isbn_num',
        ),
        migrations.AddField(
            model_name='isbn',
            name='book_author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
