# Generated by Django 3.2 on 2021-04-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210422_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Categories',
            field=models.ManyToManyField(blank=True, null=True, to='books.Category'),
        ),
    ]
